# SPDX-License-Identifier:	MPL-2.0

if(${OPUSARIUM_CMAKE_COMPILER_INCGUARD})
    return()
endif()
set(OPUSARIUM_CMAKE_COMPILER_INCGUARD TRUE)

if(${CMAKE_C_COMPILER_ID} STREQUAL "GNU")
    if(${CMAKE_VERSION} VERSION_LESS "3.12.0")
        add_definitions(-DOPUSARIUM_BUILD_COMPILER_GCC)
    else()
        add_compile_definitions(OPUSARIUM_BUILD_COMPILER_GCC)
    endif()
    set(OPUSARIUM_CMAKE_COMPILER_NAME "gcc")
elseif(${CMAKE_C_COMPILER_ID} STREQUAL "Clang")
    if(${CMAKE_VERSION} VERSION_LESS "3.12.0")
        add_definitions(-DOPUSARIUM_BUILD_COMPILER_CLANG)
    else()
        add_compile_definitions(OPUSARIUM_BUILD_COMPILER_CLANG)
    endif()
    set(OPUSARIUM_CMAKE_COMPILER_NAME "clang")
elseif(${CMAKE_C_COMPILER_ID} STREQUAL "Intel")
    if(${CMAKE_VERSION} VERSION_LESS "3.12.0")
        add_definitions(-DOPUSARIUM_BUILD_COMPILER_ICC)
    else()
        add_compile_definitions(OPUSARIUM_BUILD_COMPILER_ICC)
    endif()
    set(OPUSARIUM_CMAKE_COMPILER_NAME "icc")
elseif(${CMAKE_C_COMPILER_ID} STREQUAL "MSVC")
    if(${CMAKE_VERSION} VERSION_LESS "3.12.0")
        add_definitions(-DOPUSARIUM_BUILD_COMPILER_MSVC)
    else()
        add_compile_definitions(OPUSARIUM_BUILD_COMPILER_MSVC)
    endif()
    set(OPUSARIUM_CMAKE_COMPILER_NAME "msvc")
else()
    message(FATAL_ERROR "Unsupported Compiler: ${CMAKE_C_COMPILER_ID}")
endif()
message(STATUS "Opusarium compiler detected: ${OPUSARIUM_CMAKE_COMPILER_NAME}")
